### PR TITLE
PWA implemented

### PR DESCRIPTION
**Pull request by Satyam1203**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Motivation

I have worked in single page applications and PWA provides native like features, so I found this issue matching what I can do.

## Related PRs and Issues

#2 PWA Implementation Done.

### CODE REVIEW

**Review by abhisheknaiidu — COMMENTED** [review]
Hey @Satyam1203 Nice Work, But I don't know why the thumbnails are not loading after refreshing the page again, neither it's showing the `A-POP` dialog for PWA

**Comment by Satyam1203** [comment]
@abhisheknaiidu Do you mean that "Add to home screen" Dialog?

**Comment by abhisheknaiidu** [comment]
> @abhisheknaiidu Do you mean that "Add to home screen" Dialog?

Yup, I mean the same. It just came at first when I opened the changes in the mobile browser, but after that it never came.

**Comment by Satyam1203** [comment]
> > @abhisheknaiidu Do you mean that "Add to home screen" Dialog?
> 
> Yup, I mean the same. It just came at first when I opened the changes in the mobile browser, but after that it never came.

I tried just once and it gave me a pop-up saying "Add to home screen", I didn't try it more than once... Don't know why is it not appearing again. 

I read this answer, https://stackoverflow.com/questions/44255285/add-to-home-screen-prompt-doesnt-show-up-again-if-tab-is-closed/44712586 which says if you dismissed one, it doesn't reappear until you clear cache for that site.

**Comment by abhisheknaiidu** [comment]
@Satyam1203 Yea because of caches it might be not showing, but
- It should show in Incognito Mode, neither it's showing there nw
- Also the Images are not loading in the app after I install PWA

**Comment by Satyam1203** [comment]
I'll see if I can make it work. @abhisheknaiidu

**Comment by abhisheknaiidu** [comment]
> I'll see if I can make it work. @abhisheknaiidu

Sure, if you've any doubts and want to connect with other fellow awesome developers, you can join us on discord https://discord.gg/WHGhXvW

**Pull request merged**
